name: 'Send Discord Message'
description: 'Outputs a message to Discord.'
author: molinavinicius
branding:
  icon: message-square
  color: gray-dark
inputs:
  args:
    description: 'The message to display in the Discord message.'
    required: true
  # TODO: Handle configuration through Action inputs.
runs:
  using: 'docker'
  image: 'Dockerfile'
